# Overview of Concepts

---

## Lists

**Creating a list**:

```python
my_list = [2, 6, 9, 12]
data = ["hello", "world", "!"]
```

**Modifying lists**:

```python
nums = [42, 100]

nums.append(8)
nums.insert(0, 200)
nums.append(51)

print(nums)
```

**Accessing list elements**:

```python
nums = [4, 78, 3, 9]

print(nums[2])
print(nums[-1])

```

**Concatenating Lists**:

```python
left = [1, 2, 3]
right = [4, 5, 6]

new = left + right
print(new)
```

**Removing items from Lists**:

```python
data = [4, 8, 12, 16, 20]

num1 = data.pop(2)
num2 = data.pop(-2)

print(data)

```

**Iterating Lists**:

1) Index-iteration

```python
nums = [10, 20, 30, 40]

for i in range(len(nums)):
   print(nums[i])
```

2) For-each loop

```python
nums = [10, 20, 30, 40]

for num in nums:
   print(num)
```

**Membership**:

```python
# Check if item is in List:
data1 = ["a", "b", "c"]
x = "b"

print(x in data1)
```

----

## Dictionaries

**Creating a dictionary**:

```python
nums = {"num1": 42, "num2": 100, "num3": 8}
data = {"foo": 8.2, 100: "bar"}

print(nums)
print(data)
```

**Accessing dictionary elements**:

```python
heights = {"Charles": 175, "Adam": 160, "Florence": 180}

print(heights["Adam"])
print(heights["Florence"])
```

**Modifying dictionaries**:

```python
data = {"a": 42, "b": 3}


# Adding new keys:
data["c"] = 800
data["d"] = 4.5
print(data)

# Modifying values of existing keys:
data["a"] = 10
data["b"] = 3.2
print(data)

```

**Deleting dictionary entries**:

```python
data = {"a": 42, "b": 3, "c": 100}

del data["a"]
del data["c"]
print(data)
```

**Iterating Dictionaries**:

1) Key-iteration

```python
data = {"a": 4, "f": 1, "z": 8}

for key in data:
   value = data[key]
   print(key, value)
```

2) For-each loop

```python
data = {"a": 4, "f": 1, "z": 8}

for key, value in data.items():
  print(key, value)
```

**Membership**:

```python
# Check if key is in Dictionary:
data3 = {"a": 10, "b": 20}
z = "b"

print(z in data3)
```

----

## Sets


**Creating a set**:

```python
nums = {42, 100, 42}
data = {"A", "C", "D"}

print(nums)
print(data)
```

**Add elements to a set**:

```python
nums = {42, 100}

nums.add(8)
```

**Remove elements from a set**:

```python
nums = {42, 100}

nums.remove(100)
```

**Set Theory**:

```python
set1 = {"A", "B", "C"}
set2 = {"B", "C", "D"}

# Union:
print(set1 | set2)

# Intersection
print(set1 & set2)

# Difference
print(set1 - set2)
```

----

## Functions

**Function with no arguments**:
```python
def create_list():
   return [2, 9, 4]

```

**Function of one argument**:
```python
def add_100(a):
   return a + 100
```

**Function of two arguments**:
```python
def multiply(a, b):
   return a * b
```

**Calling a function**:
```python
def is_even(n):
   return n % 2 == 0

x = is_even(2)
print(x)
```

---

# Pandas

### Importing Pandas

```python
import pandas as pd
import numpy as np
```

### Load a DataFrame

```python
df = pd.read_csv("titanic_dataset.csv")
df
```

### Boolean Indexing

Select all passengers older than 30:
```python
df[df["Age"] > 30]
```

Select all passengers in first class:
```python
df[df["Pclass"] == 1]
```

### Chain-Indexing

Use `|` for **OR**, use `&` for **AND**.
Must use together with brackets.

Passengers that are **either** in 1st class **or** in second class:
```python
df[(df["Pclass"] == 1) | (df["Pclass"] == 2)]
```

Passengers that are in 1st class **and** and younger than 18:
```python
df[(df["Pclass"] == 1) & (df["Age"] < 18)]
```

### Data-Analysis

You may use either of `.mean()`, `.count()`, `.max()` or `.min()`.

Get the maximum fare paid by passengers:
```python
df["Fare"].max()
```

Get the minimum age of passengers which have survived:
```python
df[df["Survived"] == 1]["Age"].min()
```

### Grouping

Get the number of passengers embarked from each harbour:
```python
df.groupby("Embarked")["Name"].count()
```

Get the percentage of people that survived for each passenger class:
```python
df.groupby("Pclass")["Survived"].mean()
```

### Using it all together

1. First we use boolean indexing
2. Secondly we use grouping
3. Finally we use data analysis functions

Get the number of passengers, aged below 18, that survived, grouped by each passenger class:
```python
df[df["Age"] < 18].groupby("Pclass")["Survived"].count()
```

---